---
title: "Predicht Stock movement based on Price Action"
output:
  html_document:
    df_print: paged
editor_options:
  markdown:
    wrap: 72
---

```{r}
library(knitr)
read_chunk(here::here("02_R/Price_Action.R"))
```

# Idee

Verwenden eines Cluster Algorythmus um Aktien in Cluster Up und down zu
clustern.

Clustern der Aktien anhand ausgewählter Indikatoren in buy od sell
Aktien. Buy = wenn Closing Price d+x \> Closing Price d Sell = wenn
Closing Price d+x \< Closing Price d

Kein time Series sondern clustern anhand von Indikatoren

# Indikatoren

## 1. Price Action

Verwenden eines Price Action Indikators [Price Action Medium
Artikel](https://medium.com/swlh/400-trading-algorithms-later-bc76279bc525){.uri}

Thorie: mittels Price Action können Price entwicklungen besser
vorhergesagt werden als mit Lagging indikatoren.

-   how many upward (bullish) periods (candles) occurred during the past
    movement vs downward (bearish);

-   what is the average bullish candle body size vs bearish;

-   how many bullish candles occur in a row on average vs bearish;

-   what is the average upper wick (tail) size vs lower; how much do the
    candles overlap on average.

-   **Strength buffer** will calculate the relative strength of the
    price action compared to the inputted 'Period' amount of past
    candles. An upward movement of this line indicates a bullish price
    action strength while a downward movement of this line indicates a
    bearish price action strength. The higher this line is, the more
    bullish the price action strength is, the lower the line, the more
    bearish the price action strength;

-   **Overlap buffer** will calculate the relative overlapping of the
    current bars compared to the inputted 'Period' amount of past
    candles. The information is visualized using a histogram. The higher
    the histogram, the stronger the price action strength considering
    the overlapping of the bars. In other words, the higher the
    histogram gets, the less overlapping exists between the bars,
    meaning the price has a concrete direction and it doesn't range,
    which indicates a strong move;

-   **Reversal buffer** The reversal arrow indicates that the reversal
    of the price is likely. Reversal signals are the ones that produce
    the most false signals, but if correct, they predict the biggest
    moves. It is recommended to use a risk/reward of at least 2 or
    bigger when taking these signals; Recent peaks/bottoms of the price
    compared to the Price Action Strength value

-   **Continuation buffer** is indicated with a slanted arrow. The
    continuation arrow indicates that the market is gaining momentum in
    the corresponding direction. These signals often appear during an
    ongoing trend and are meant as a supportive indication that the
    market will more likely continue on the current course. Continuation
    signals provide more accurate predictions, but the market moves
    following are often not huge. It is recommended to use these signals
    for adding on to trend trades or scalps; Confirmation buffer is
    indicated with a thick upwards/downwards arrow. The confirmation
    arrow shows up when both the reversal and continuation signals
    appears during the same candle. This indicates a highly probable
    move. Continuation/momentum sentiment, which is calculated using the
    Price Action Strength momentum and value
    


## 2.  Cluster

## 3. Test
